### ISSUE TITLE
Sizing of PNGs in Rmd to Quarto 

### ISSUE THREAD

**Issue by IleanaF** [Openscapes/lab-manual#2]
**Please tell us how to make the hex image smaller**

We are trying to make these lines of code Quarto compatible 

Original from Faylab manual 
```{r, out.width = "25%", echo = FALSE}
knitr::include_graphics("https://allisonhorst.github.io/img/openscapes_hex_badge.png")
```

So far we have 
`![](img/openscapes_hex_badge.png){width ="25%"}`

or 

`![](img/openscapes_hex_badge.png){width ="100px"}`

Note the image has been placed in the img file as opposed to linked from Git

**Comment by jules32** [comment]
This approach seems really good @IleanaF. I like having a copy of the img file inside the lab-manual repository. And sizing it with `{width}` is great!

**Comment by stefaniebutland** [comment]
This issue fixed and closed by https://github.com/Openscapes/lab-manual/pull/11 thanks to @IleanaF
