### ISSUE TITLE
Referencing System Date from Rmd to Quarto

### ISSUE THREAD

**Issue by IleanaF** [Openscapes/lab-manual#3]
**Seeking to publish the last updated date referenced in R**

![Screen Shot 2022-06-13 at 4 17 48 PM](https://user-images.githubusercontent.com/84345754/173437959-f77ca73e-68d9-456b-b17d-ffde3ea330f8.png)

`date: "Last updated: `r Sys.date()`" `

This line no longer shows the most recent date like below when copied over 
![Screen Shot 2022-06-13 at 4 19 33 PM](https://user-images.githubusercontent.com/84345754/173438197-9414e1e1-8272-4d1b-8e64-9c8e4ca7b651.png)

**Comment by stefaniebutland** [comment]
Found this in Quarto docs

https://quarto.org/docs/reference/dates.html
