### ISSUE TITLE
remove `_output.yml`

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/lab-manual#5]
According to [Nick Tierney's post](https://www.njtierney.com/post/2022/04/11/rmd-to-qmd/) "Change _bookdown.yml to _quarto.yml and remove _output.yml"

Do this after checking that `_output.yml` content is contained in `_quarto.yml`

**Comment by jules32** [comment]
Let's try adding a link to Gavin's website (previously in `_output.yml`: https://github.com/Openscapes/lab-manual/blob/main/_output.yml#L7 ) to the page footer. Example: https://github.com/hadley/r4ds/blob/15349e86af74298ba83e5de628f48a40edc3569a/_quarto.yml#L25-L30

**Comment by stefaniebutland** [comment]
`_output.yml` had pdf and epub formats noted, but I'm not sure how to implement these in quarto and if they were used in the original book.

**Comment by stefaniebutland** [comment]
ready to delete now

**Comment by stefaniebutland** [comment]
done in https://github.com/Openscapes/lab-manual/pull/12
