### ISSUE TITLE
Decide whether to use Quarto Book Crossrefs

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/lab-manual#8]
From Quarto docs on [Book Crossrefs](https://quarto.org/docs/books/book-crossrefs.html)
> One important difference between creating a website and a book is that in addition to their web output, books can also be rendered as a single continuous document (e.g a PDF or MS Word document). Books also may or may not be read digitally (which means that internal hyperlinks may or may not be available).

> To create books that are consumable in all of these mediums, special care should be taken when creating links to other chapters or sections within chapters (note though that if your book targets only HTML output you can feel free to use conventional hyperlinks).

**Comment by jules32** [comment]
I think this is a good way to go for Gavin

**Comment by stefaniebutland** [comment]
We decided not to implement this now. Gavin might do as he reviews the manual content.
